### ISSUE TITLE
no iptables exists for standard playbook

### ISSUE THREAD

**Issue by cinchcircuits** [cinchcircuits/bamru_truck#1]
TASK: [roles/hotspot_rpi | enable NAT in the kernel] *************************\* 
failed: [bpi-plus-1] => (item=iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE) => {"changed": true, "cmd": "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE", "delta": "0:00:00.019853", "end": "2015-05-05 23:01:42.238864", "item": "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE", "rc": 3, "start": "2015-05-05 23:01:42.219011", "warnings": []}
stderr: FATAL: Module ip_tables not found.
iptables v1.4.14: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
failed: [bpi-plus-1] => (item=iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT) => {"changed": true, "cmd": "iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT", "delta": "0:00:00.020272", "end": "2015-05-05 23:01:42.693763", "item": "iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT", "rc": 3, "start": "2015-05-05 23:01:42.673491", "warnings": []}
stderr: FATAL: Module ip_tables not found.
iptables v1.4.14: can't initialize iptables table`filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
failed: [bpi-plus-1] => (item=iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT) => {"changed": true, "cmd": "iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT", "delta": "0:00:00.017946", "end": "2015-05-05 23:01:43.149465", "item": "iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT", "rc": 3, "start": "2015-05-05 23:01:43.131519", "warnings": []}
stderr: FATAL: Module ip_tables not found.
iptables v1.4.14: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

FATAL: all hosts have already failed -- aborting

**Comment by cinchcircuits** [comment]
It looks to be a issue with the banana pi m2 I am using. It appears that the iptables modules are not built for it.

**Comment by cinchcircuits** [comment]
There appears to be a new kernel available for me to try.
Relevant links here:
http://www.igorpecovnik.com/2014/09/07/banana-pi-debian-sd-image/
http://www.bananapi.com/index.php/forum/raspbian/544-iptables-nftables-support#2090
https://github.com/igorpecovnik/lib/blob/next/config/linux-sunxi-next.config

**Comment by cinchcircuits** [comment]
Building kernel howto.

**Comment by andyl** [comment]
I ran into this problem this eve.  I updated the hotspot role to run:
- sudo modprobe ip_tables
- sudo echo ip_tables >> /etc/modules

That seemed to fix the problem.  Can we close this issue now?

**Comment by cinchcircuits** [comment]
Unfortunately, this issue relates to the banana pi m2 I am using. This does not apply to the rpi2 at all. 

We can close it. i believe that we are going to specify using a rpi2 for now.

**Comment by andyl** [comment]
closed.
