### ISSUE TITLE
Intel Edison

### ISSUE THREAD

**Issue by andyl** [cinchcircuits/bamru_truck#10]
This isn't a bug report - a post with some project-related notes.

I studied Intel Edison a bit this morning.  It looks like an interesting product - size is great - not nearly as well supported as RPi - 2x more expensive than RPi.  Some people are building wifi hotspots with Edison - looks like they encounter as many or more issues as we see on the RPi.

Here are some edison links:
http://topusefulsolutions.com/263358/intel-edison-as-a-wi-fi-hotspot-using-external-usb-to-ethernet-adapter-and-wlan
http://www.instructables.com/id/Intel-Edison-Webcam-via-Hotspot/step2/Make-your-Edison-hotspot/
https://software.intel.com/en-us/articles/intel-iot-getting-started-with-access-point-ap-mode
https://communities.intel.com/thread/58633
https://communities.intel.com/docs/DOC-23391

**Comment by cinchcircuits** [comment]
Interesting. 

I have a edison with a dev board. I'll try it out when I can in the next 2 weeks.

**Comment by cinchcircuits** [comment]
loaded up a intel edison with a new OS tonight. 

Will need to test it out later. Getting too late tonight.

**Comment by andyl** [comment]
So - RPi is working fine - should we mark this as closed??

**Comment by andyl** [comment]
marking as closed
