### ISSUE TITLE
udhcpd not auto-starting after reboot

### ISSUE THREAD

**Issue by andyl** [cinchcircuits/bamru_truck#7]
have to run command 'sudo service udhcpd start' after reboot...

**Comment by cinchcircuits** [comment]
Confirmed with a caveat. 

Neither hostapd or udhcpd not running on startup 

pi@rpi3 ~ $ ps -fax | grep hostap
warning: bad ps syntax, perhaps a bogus '-'?
See http://gitorious.org/procps/procps/blobs/master/Documentation/FAQ
 2585 pts/0    S+     0:00              _ grep --color=auto hostap

pi@rpi3 ~ $ ps -fax | grep udhc
warning: bad ps syntax, perhaps a bogus '-'?
See http://gitorious.org/procps/procps/blobs/master/Documentation/FAQ
 2587 pts/0    S+     0:00              _ grep --color=auto udhc

Although, after I fixed the hostapd to match my funky adapter, it works through a reboot. 

Is this still a issue.

**Comment by andyl** [comment]
I merged your PR, then posted a couple of other updates.  Have been able to successfully build a new system and reboot it.  Marking this closed.
