### ISSUE TITLE
Intermittent Failure

### ISSUE THREAD

**Issue by andyl** [cinchcircuits/bamru_truck#9]
I've been streaming video and audio all evening on a single laptop thru the RPi Hotspot.  About every 30 minutes or so, the connection dies.  Workaround is to reboot the laptop.

**Comment by cinchcircuits** [comment]
At Fetch, we have been starting to use atheros cards because they seem to be  a lot more stable than realteck and intel cards. 

Others on the internet report that AR9271 cards work well. 

I am ordering one of these to try out:

http://www.amazon.com/Docooler-Adapter-150Mbps-Atheros-Antenna/dp/B00IZ5GNSA

**Comment by andyl** [comment]
Thanks for the tip - just bought one.

**Comment by cinchcircuits** [comment]
Mine isn't supposed to arrive until the beginning of next month :(

This is the card we like the most:

http://www.amazon.com/gp/product/B00OJPJT8Q/ref=oh_aui_detailpage_o06_s00?ie=UTF8&psc=1

This weekend, I'll plug one into the mini pci-e to usb converter I have to see if it works. If it does, I will try it out in this project. 

Those chips have a usb interface on them. This thing might just work.

https://wikidevi.com/files/Atheros/specsheets/AR9462.pdf

**Comment by andyl** [comment]
2x more expensive but worth it if that solves the stability problem.

If bluetooth works might be interesting to look into BLE/iBeacon for the RPi.

I streamed youtube audio thru one of the RPi's all day today with perfect reliability.

Some differences from yesterday's failed test:
1) streamed to a different laptop which has older and IMHO more stable drivers (u14.04 64bit)
2) the laptop was 8 inches from the RPi (yesterday was 10-15 feet)
3) audio instead of video - big difference in data rates.

I'll try streaming video tomorrow.

**Comment by cinchcircuits** [comment]
Using those pci-e cards will be more than 2x as expensive as to use them,
you would also need a pci-e to usb breakout.

Such as this:
www.amazon.com/Generic-Wireless-Adapter-Module-Testing/dp/B00EQ1UFNG/ref=sr_1_5?ie=UTF8&qid=1431534747

Then, you would need a adapter to put the half height card into the full
size slot, like this:
http://www.amazon.com/Height-Express-PCI-E-Bracket-Adapter/dp/B007VXJ9IS/ref=sr_1_4?ie=UTF8&qid=1431534929

Finally, you would need two antennas, such as this:
http://www.amazon.com/Wi-fi-Antenna-RP-SMA-Antennas-Cables/dp/B00A4I3AGE/ref=sr_1_4?ie=UTF8&qid=1431534957

That being said, I do not know if this would be more stable or not. I'll
need to try it here to see.

I should be able to let you know next week.

Michael-

**Comment by andyl** [comment]
Now I've streamed audio and video for 20 hours straight / ~2gigs of data - no dropped packets or dropped connections.  Memory and CPU consumption on the RPi are barely noticeable.  So for a single-user scenario, with the laptop inches from the RPi, it's looking good!  ;-)

Next tests: 
- move the stable laptop across the room
- move the flaky laptop within inches of the RPi

**Comment by cinchcircuits** [comment]
Notes found regarding running hostapd on a AR9462

http://ubuntuforums.org/showthread.php?t=1367334&page=2&s=f35bf109e826a5ea5dae6a3065be2a3a

**Comment by andyl** [comment]
Streamed all day - flawless.  Two laptops streaming from one RPi - no problemo. Flakey laptop next to the pi, stable laptop across the room.  Then I swapped the laptop positions.  Five minutes later, the flaky laptop dropped the connection.  So the failure seems repeatable, and is distance related.

**Comment by cinchcircuits** [comment]
Invalid at this point. 
Closing.
